### ISSUE TITLE
Initial release checklist

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-celery#1]
- [x] basic celery setup (shared task)
- [x] default setup to work with aldryn-django and on the aldryn platform
- [x] clean aldryn startup integration (Procfile? ~~direct? as command in aldryn-django?~~ as its own command?)
- [x] default setup using postgres scheduler
- [x] default setup using postgres result backend
- [x] 
  ~~`use`celeryd -e`and run`celerycam`? Does`celerycam`need the same locking as`celerybeat``?~~ _celerycam can be launched in the generic way now. Long term it is depricated in favor of  `flower`. Unfortunatly `flower` is a bit tricky to setup in a generic way on aldryn (without wasting resources)._
- [x] make sure old results are purged from the database
- [x] hide irrelevant djcelery tables in admin
- [x] show minimal task results in admin
- [x] release as Addon on aldryn (private)
- [x] test the released Addon on at least one existing project
